# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://jstools.dev/eslint-config/

root: true
extends: "@jsdevtools"
parserOptions:
  sourceType: module
env:
  node: true
  browser: true
rules:
  "@typescript-eslint/no-explicit-any": ["off"]
