# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://jstools.dev/eslint-config/

root: true
env:
  node: true
  browser: true
parserOptions:
  sourceType: module
extends: "@jsdevtools"
rules:
  # Added to help with ESMification
  '@typescript-eslint/no-require-imports': 2

  # TODO Remove this hack, I was just desperate to get this 'working'. -Phil
  '@typescript-eslint/no-explicit-any': 'off'
