version: 2.1

orbs:
  node: circleci/node@4.7.0
  browser-tools: circleci/browser-tools@1.4.4

executors:
  linux:
    docker:
      - image: cimg/base:2022.02

commands:
  install:
    steps:
      - run:
          name: Install dependencies
          command: npm ci

  test-node:
    steps:
      - run:
          name: Lint the code
          command: npm run lint
      - run:
          name: Run node tests
          command: npm run test:node
      - run:
          name: Verify typings
          command: npm run test:typescript

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>.0
          install-yarn: false
          install-npm: true
          npm-version: "9.7.1"
      - install
      - test-node

  test-browser:
    docker:
      - image: cimg/node:16.13-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - install
      - run:
          name: Run browser tests
          command: npm run test:browser

workflows:
  commit:
    jobs:
      - test:
          matrix:
            parameters:
              os:
                - linux
              node-version:
                - "14.19"
                - "16.13"
      - test-browser
